[project]
name = "PyGasMix"
version = "1.3.0"
requires-python = ">=3.8"
dependencies = []

[build-system]
requires = ["setuptools", "Cython==0.29.37", "numpy"]
build-backend = "setuptools.build_meta"
